In [5]:
import numpy as np

arr = np.array([1,2,3,4,5]) #создание массива
zeros = np.zeros((4,4)) #матрица с нулями
ones = np.ones((3,2)) #матрица единиц
eye = np.eye(3) #создание единичной матрицы 
empty = np.empty((5,2)) #Создание пустой матрицы
a = np.arange(10,30,5)
arr, zeros, ones, eye, empty, a

(array([1, 2, 3, 4, 5]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[6.95323904e-310, 6.95316929e-310],
        [6.95323904e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.11253693e-308]]),
 array([10, 15, 20, 25]))

In [ ]:
import numpy as np

a = np.ones((3,2))
b = 5*np.transpose(a) #Транспонирование
a,b, a.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[5., 5., 5.],
        [5., 5., 5.]]),
 (3, 2))

In [ ]:
a = np.arange(1,8)
a, a[3],a[2:5] 

(array([1, 2, 3, 4, 5, 6, 7]), np.int64(4), array([3, 4, 5]))

In [13]:
ar = np.array([[1,2,3,4],[5,6,7,8]])

for el in ar.flat: 
    print(el)
ar.ravel() #создание копии (делает матрицу в строчку)
ar.shape = (4,2)
ar

1
2
3
4
5
6
7
8


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
arr = np.array([[1,2],[3,4]])
brr = np.array([[5,6],[7,8]])

np.vstack((arr,brr)), np.hstack((arr,brr)) # объединяет массивы по вертикальным осям, объединяет массивы по горизонтальным осям соответственно

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

In [ ]:
np.column_stack((arr, brr)), np.row_stack((arr,brr)) #первый вариант по горизонтальным осям, второй вариант устарел

C:\Users\giver\AppData\Local\Temp\ipykernel_58156\3199382858.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.column_stack((arr, brr)), np.row_stack((arr,brr))


(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [ ]:
#hsplit предназначается для разделения по столбцам
#vsplit предназначается для разделения по строчкам

#copy создает НЕЗАВИСИМУЮ копию элемента
#view создает представление (изменение одного изменит другое)

In [46]:
#Рандомные числа 
import numpy.random as rand

rand.sample()

0.8357299882519368

In [56]:
a = -3 
b = 5

a + (b - a)*rand.sample() #случайное число из диапозона [a,b)

3.7538734460190977

In [ ]:
rand.randint(0, 3, (2, 10)) #двумерный массив случайных числе от 0 до 2

array([[0, 1, 0, 2, 2, 2, 0, 0, 1, 1],
       [2, 0, 2, 0, 0, 1, 1, 2, 2, 2]], dtype=int32)

In [61]:
rand.uniform(2, 8, (2, 10)) #двумерный массив случайных числе от 2 до 8

array([[4.64515616, 2.14802059, 5.38712213, 2.87512495, 2.53969659,
        6.46425585, 4.85469924, 3.37228695, 3.65481485, 7.24912479],
       [5.31449932, 2.35821736, 4.65928162, 4.88422355, 4.64683946,
        5.36325772, 7.56187975, 2.35695037, 2.92414736, 3.09553159]])

In [84]:
arr = rand.randint(1, 4, (3, 4))
print(arr)
rand.shuffle(arr)
arr

[[2 3 3 1]
 [3 1 2 1]
 [1 1 1 1]]


array([[2, 3, 3, 1],
       [3, 1, 2, 1],
       [1, 1, 1, 1]], dtype=int32)

In [85]:
rand.seed(42)
rand.random(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [10]:
data = np.arange(1, 11)  

print("Сумма элементов:", data.sum())
print("Среднее значение:", data.mean())
print("Максимум:", data.max())
print("Минимум:", data.min())
print("Стандартное отклонение:", data.std())


matrix = np.random.randint(1, 10, (3, 4))
print(matrix)

print("Сумма по всем элементам:", matrix.sum())
print("Среднее по всем элементам:", matrix.mean())
print("Сумма по строкам:", matrix.sum(axis=1))
print("Сумма по столбцам:", matrix.sum(axis=0))

Сумма элементов: 55
Среднее значение: 5.5
Максимум: 10
Минимум: 1
Стандартное отклонение: 2.8722813232690143
[[8 1 6 3]
 [3 7 3 9]
 [7 8 8 5]]
Сумма по всем элементам: 68
Среднее по всем элементам: 5.666666666666667
Сумма по строкам: [18 22 28]
Сумма по столбцам: [18 16 17 17]
